export const products = [
  {
    _id: "1",
    name: "Airpods",
    description: "Latest iPhone with A15 Bionic chip and Pro camera system",
    brand: "Apple",
    category: "Smartphones",
    price: 999,
    countInStock: 15,
    rating: 5,
    numReviews: 120,
    image: "./images/airpods.jpg",
  },
  {
    _id: "2",
    name: "Alexa",
    description: "Powerful Android phone with Dynamic AMOLED display",
    brand: "Samsung",
    category: "Smartphones",
    price: 799,
    countInStock: 20,
    rating: 2.6,
    numReviews: 95,
    image: "./images/alexa.jpg",
  },
  {
    _id: "3",
    name: "Camers",
    description: "High-performance laptop with Apple Silicon",
    brand: "Apple",
    category: "Laptops",
    price: 1299,
    countInStock: 8,
    rating: 4.9,
    numReviews: 200,
    image: "./images/camera.jpg",
  },
  {
    _id: "4",
    name: "Mouse",
    description: "Premium noise-canceling wireless headphones",
    brand: "Sony",
    category: "Headphones",
    price: 349,
    countInStock: 12,
    rating: 3,
    numReviews: 150,
    image: "./images/mouse.jpg",
  },
  {
    _id: "5",
    name: "Mobile Phone",
    description: "Classic white sneakers for everyday wear",
    brand: "Nike",
    category: "Footwear",
    price: 110,
    countInStock: 30,
    rating: 2.5,
    numReviews: 85,
    image: "./images/phone.jpg",
  },
  {
    _id: "6",
    name: "Play station",
    description: "Classic white sneakers for everyday wear",
    brand: "Nike",
    category: "Footwear",
    price: 110,
    countInStock: 30,
    rating: 2.5,
    numReviews: 85,
    image: "./images/playstation.jpg",
  },
  {
    _id: "5",
    name: "Sample Image",
    description: "Classic white sneakers for everyday wear",
    brand: "Nike",
    category: "Footwear",
    price: 110,
    countInStock: 30,
    rating: .5,
    numReviews: 85,
    image: "./images/sample.jpg",
  },
];
